In [1]:
from dotenv import load_dotenv
import os
load_dotenv()

True

In [2]:
import pandas as pd
X_train=pd.read_csv("./UCI HAR Dataset/train/X_train.txt",delim_whitespace=True,header=None)
y_train=pd.read_csv("./UCI HAR Dataset/train/y_train.txt",delim_whitespace=True,header=None)

C:\Users\SHRIJAN SAHU\AppData\Local\Temp\ipykernel_45212\1488102985.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  X_train=pd.read_csv("./UCI HAR Dataset/train/X_train.txt",delim_whitespace=True,header=None)
C:\Users\SHRIJAN SAHU\AppData\Local\Temp\ipykernel_45212\1488102985.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  y_train=pd.read_csv("./UCI HAR Dataset/train/y_train.txt",delim_whitespace=True,header=None)

In [3]:
features=pd.read_csv("./UCI HAR Dataset/features.txt",delim_whitespace=True,header=None)

C:\Users\SHRIJAN SAHU\AppData\Local\Temp\ipykernel_45212\809808608.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  features=pd.read_csv("./UCI HAR Dataset/features.txt",delim_whitespace=True,header=None)

In [4]:
X_train.columns=features[1]
X_train

1,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-meanFreq(),fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)"
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,0.404573,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,0.087753,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7347,0.299665,-0.057193,-0.181233,-0.195387,0.039905,0.077078,-0.282301,0.043616,0.060410,0.210795,...,-0.070157,-0.588433,-0.880324,-0.190437,0.829718,0.206972,-0.425619,-0.791883,0.238604,0.049819
7348,0.273853,-0.007749,-0.147468,-0.235309,0.004816,0.059280,-0.322552,-0.029456,0.080585,0.117440,...,0.165259,-0.390738,-0.680744,0.064907,0.875679,-0.879033,0.400219,-0.771840,0.252676,0.050053
7349,0.273387,-0.017011,-0.045022,-0.218218,-0.103822,0.274533,-0.304515,-0.098913,0.332584,0.043999,...,0.195034,0.025145,-0.304029,0.052806,-0.266724,0.864404,0.701169,-0.779133,0.249145,0.040811
7350,0.289654,-0.018843,-0.158281,-0.219139,-0.111412,0.268893,-0.310487,-0.068200,0.319473,0.101702,...,0.013865,0.063907,-0.344314,-0.101360,0.700740,0.936674,-0.589479,-0.785181,0.246432,0.025339
7351,0.351503,-0.012423,-0.203867,-0.269270,-0.087212,0.177404,-0.377404,-0.038678,0.229430,0.269013,...,-0.058402,-0.387052,-0.740738,-0.280088,-0.007739,-0.056088,-0.616956,-0.783267,0.246809,0.036695

In [5]:
y_train

      0
0     5
1     5
2     5
3     5
4     5
...  ..
7347  2
7348  2
7349  2
7350  2
7351  2

[7352 rows x 1 columns]

In [6]:
import pandas as pd 
from langchain_groq.chat_models import ChatGroq

In [7]:
Groq_Token = os.getenv("GROQ_TOKEN")

groq_models = {"llama3-70b": "llama3-70b-8192", "mixtral": "mixtral-8x7b-32768", "gemma-7b": "gemma-7b-it","llama3.1-70b":"llama-3.1-70b-versatile","llama3-8b":"llama3-8b-8192","llama3.1-8b":"llama-3.1-8b-instant","gemma-9b":"gemma2-9b-it"}

In [8]:
",".join(X_train.iloc[0][:520].astype(str).to_list())

'0.28858451,-0.020294171,-0.13290514,-0.9952786,-0.98311061,-0.91352645,-0.99511208,-0.98318457,-0.92352702,-0.93472378,-0.56737807,-0.74441253,0.85294738,0.68584458,0.81426278,-0.96552279,-0.99994465,-0.99986303,-0.99461218,-0.99423081,-0.98761392,-0.94321999,-0.40774707,-0.67933751,-0.60212187,0.92929351,-0.85301114,0.35990976,-0.058526382,0.25689154,-0.22484763,0.26410572,-0.09524563,0.27885143,-0.46508457,0.49193596,-0.19088356,0.37631389,0.43512919,0.66079033,0.96339614,-0.14083968,0.11537494,-0.98524969,-0.98170843,-0.87762497,-0.98500137,-0.98441622,-0.89467735,0.89205451,-0.16126549,0.12465977,0.97743631,-0.12321341,0.056482734,-0.37542596,0.89946864,-0.97090521,-0.97551037,-0.98432539,-0.98884915,-0.91774264,-1.0,-1.0,0.11380614,-0.590425,0.5911463,-0.59177346,0.59246928,-0.74544878,0.72086167,-0.71237239,0.71130003,-0.99511159,0.99567491,-0.99566759,0.99165268,0.57022164,0.43902735,0.98691312,0.077996345,0.0050008031,-0.067830808,-0.99351906,-0.98835999,-0.99357497,-0.99448763,-0.98620664,-0.99281835,-0.9851801,-0.99199423,-0.99311887,0.98983471,0.99195686,0.9905192,-0.99352201,-0.99993487,-0.99982045,-0.99987846,-0.99436404,-0.98602487,-0.98923361,-0.81994925,-0.79304645,-0.88885295,1.0,-0.22074703,0.63683075,0.38764356,0.24140146,-0.052252848,0.2641772,0.37343945,0.34177752,-0.56979119,0.26539882,-0.47787489,-0.3853005,0.033643943,-0.12651082,-0.0061008489,-0.031364791,0.1077254,-0.98531027,-0.97662344,-0.99220528,-0.98458626,-0.97635262,-0.99236164,-0.86704374,-0.93378602,-0.74756618,0.84730796,0.91489534,0.83084054,-0.96718428,-0.99957831,-0.99935432,-0.99976339,-0.98343808,-0.97861401,-0.99296558,0.082631682,0.20226765,-0.16875669,0.096323236,-0.27498511,0.49864419,-0.22031685,1.0,-0.97297139,0.31665451,0.37572641,0.72339919,-0.77111201,0.69021323,-0.33183104,0.70958377,0.13487336,0.30109948,-0.0991674,-0.055517369,-0.061985797,-0.99211067,-0.99251927,-0.99205528,-0.99216475,-0.99494156,-0.99261905,-0.99015585,-0.98674277,-0.99204155,0.99442876,0.99175581,0.98935195,-0.99445335,-0.99993755,-0.9999535,-0.99992294,-0.99229974,-0.99693892,-0.99224298,-0.58985096,-0.68845905,-0.57210686,0.29237634,-0.36199802,0.40554269,-0.039006951,0.98928381,-0.41456048,0.39160251,0.28225087,0.92726984,-0.57237001,0.6916192,0.46828982,-0.13107697,-0.087159695,0.33624748,-0.95943388,-0.9505515,-0.95799295,-0.94630524,-0.99255572,-0.95943388,-0.99849285,-0.9576374,-0.23258164,-0.17317874,-0.02289666,0.094831568,0.19181715,-0.95943388,-0.9505515,-0.95799295,-0.94630524,-0.99255572,-0.95943388,-0.99849285,-0.9576374,-0.23258164,-0.17317874,-0.02289666,0.094831568,0.19181715,-0.99330586,-0.99433641,-0.99450037,-0.99278399,-0.99120847,-0.99330586,-0.99989188,-0.9929337,-0.86341476,0.28308522,-0.23730869,-0.10543219,-0.038212313,-0.96895908,-0.96433518,-0.95724477,-0.97505986,-0.99155366,-0.96895908,-0.99928646,-0.94976582,0.072579035,0.57251142,-0.73860219,0.21257776,0.43340495,-0.99424782,-0.99136761,-0.99314298,-0.98893563,-0.99348603,-0.99424782,-0.99994898,-0.99454718,-0.61976763,0.29284049,-0.1768892,-0.14577921,-0.12407233,-0.99478319,-0.9829841,-0.93926865,-0.99542175,-0.98313297,-0.90616498,-0.99688864,-0.98451927,-0.932082,-0.99375634,-0.98316285,-0.88505422,-0.99396185,-0.99344611,-0.92342772,-0.97473271,-0.99996838,-0.99968911,-0.99489148,-0.99592602,-0.98970889,-0.98799115,-0.94635692,-0.90474776,-0.59130248,-1.0,-1.0,-1.0,0.2524829,0.13183575,-0.052050251,0.14205056,-0.1506825,-0.22054694,-0.55873853,0.24676868,-0.0074155206,-0.99996279,-0.9999865,-0.99997907,-0.99996244,-0.99993222,-0.99972512,-0.99967039,-0.99998582,-0.99996867,-0.99997686,-0.99986966,-0.99977613,-0.99997115,-0.99991925,-0.9996568,-0.99986046,-0.99986695,-0.99986301,-0.99973783,-0.9997322,-0.99949261,-0.99981364,-0.99968182,-0.9998394,-0.99973823,-0.99961197,-0.99968721,-0.99983863,-0.99359234,-0.99947584,-0.99966204,-0.9996423,-0.99929341,-0.99789222,-0.99593249,-0.99514642,-0.9947399,-0.99968826,-0.99892456,-0.99567134,-0.99487731,-0.99945439,-0.99233245,-0.98716991,-0.98969609,-0.99582068,-0.99093631,-0.99705167,-0.99380547,-0.99051869,-0.99699279,-0.99673689,-0.99197516,-0.99324167,-0.99834907,-0.99110842,-0.95988537,-0.99051499,-0.99993475,-0.99982048,-0.99988449,-0.99302626,-0.99137339,-0.99623962,-1.0,-1.0,-1.0,1.0,-0.24,-1.0,0.87038451,0.210697,0.26370789,-0.70368577,-0.90374251,-0.58257362,-0.93631005,-0.50734474,-0.80553591,-0.99998649,-0.9999796,-0.99997478,-0.99995513,-0.99991861,-0.99964011,-0.9994833,-0.99996087,-0.99998227,-0.99997072,-0.99981098,-0.99948472,-0.99998083,-0.99985189,-0.99993261,-0.99989993,-0.99982444,-0.99985982,-0.99972751,-0.99972876,-0.99956707,-0.99976524,-0.99990021,-0.9998149,-0.9997098,-0.99959608,-0.99985216,-0.9998221,-0.99939988,-0.99976559,-0.99995846,-0.99994951,-0.9998385,-0.99981351,-0.99878054,-0.99857783,-0.99961968,-0.99998359,-0.99982812,-0.99868068,-0.99984416,-0.99992792,-0.98657442,-0.98176153,-0.98951478,-0.98503264,-0.97388607,-0.99403493,-0.98653085,-0.98361636,-0.99235201,-0.98049843,-0.97227092,-0.99494426,-0.99756862,-0.9840851,-0.99433541,-0.98527621,-0.99986371,-0.99966608,-0.99993462,-0.99034389,-0.99483569,-0.99441158,-0.71240225,-0.64484236,-0.83899298,-1.0,-1.0,-1.0,-0.25754888,0.097947109,0.54715105,0.37731121,0.13409154,0.27337197,-0.091261831,-0.4843465,-0.7828507,-0.99986502,-0.99993178,-0.99997295,-0.99997018,-0.99993012,-0.99995862,-0.99992899,-0.99998465,-0.99986326,-0.99996815,-0.9999361,-0.99995363,-0.99986442,-0.99996098,-0.99945373,-0.99997811,-0.99999153,-0.9999901,-0.99996857,-0.99980657,-0.998346,-0.99896122,-0.99961874,-0.99998934,-0.9999354,-0.99838752,-0.99964264,-0.99997266,-0.99995535,-0.9999763,-0.99990583,-0.9999855,-0.99993717,-0.99975115,-0.99907227,-0.99992754,-0.99995158,-0.99990585,-0.99989269,-0.99944433,-0.99994099,-0.99995861,-0.95215466,-0.95613397,-0.94887014,-0.97432057,-0.92572179,-0.95215466,-0.9982852,-0.9732732,-0.64637645,-0.79310345,-0.08843612,-0.43647104,-0.79684048,-0.99372565,-0.99375495,-0.9919757,-0.99336472,-0.98817543'

In [9]:
sentence = ','.join(X_train.iloc[0][:520].astype(str).to_list())

# System Prompts 
query = f"""
* You are a classifier 
* Your task is to classify on the basis of the given features into WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING
* Answer in one word only.

Sentence: {sentence}
""" 

# To use Groq LLMs 
model_name = "llama3-70b" # We can choose any model from the groq_models dictionary
llm = ChatGroq(model=groq_models[model_name], api_key=Groq_Token, temperature=0)
answer = llm.invoke(query)

print(answer.content)

LAYING

In [10]:
sentence = ','.join(X_train.iloc[0][:520].astype(str).to_list())

# System Prompts 
query = f"""
* You are a classifier 
* Your task is to classify on the basis of the given features into WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING
* Answer in one word only.

Sentence: {sentence}
""" 

# To use Groq LLMs 
model_name = "llama3-70b" # We can choose any model from the groq_models dictionary
llm = ChatGroq(model=groq_models[model_name], api_key=Groq_Token, temperature=0)
answer = llm.invoke(query)

print(answer.content)

LAYING

In [11]:
test_prediction=[]
for i in range(10):
     
    sentence = ','.join(X_train.iloc[i][:520].astype(str).to_list())
    # System Prompts 
    query = f"""
    * You are a classifier.
    * Your task is to classify human activities based on the given features into one of the following categories: WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING.
    * Use the examples provided below to inform your classification.
    * Answer in one word only.

    Examples:
    - Features: [0.1, 0.2, 0.3, ...] -> WALKING
    - Features: [0.5, 0.6, 0.7, ...] -> STANDING
    - Features: [0.2, 0.4, 0.6, ...] -> SITTING

    Now, classify the following features:
    - Features: {sentence}
    """


    # To use Groq LLMs 
    model_name = "llama3-70b" # We can choose any model from the groq_models dictionary
    llm = ChatGroq(model=groq_models[model_name], api_key=Groq_Token, temperature=0)
    answer = llm.invoke(query)
    test_prediction.append(answer.content)
    print(answer.content)

STANDING

In [ ]:
# Statement 
sentence = "The product quality is amazing but the delivery was delayed. However I am happy with the customer service."

# System Prompts 
query = f"""
* You are a sentiment analysis model. 
* Your task is to analyze the sentiment expressed in the given text and classify it as 'positive', 'negative', or 'neutral'. 
* Provide the sentiment label and, if necessary, a brief explanation of your reasoning.

Here are few examples:
1. Sentence: 'The customer service was excellent, and I received my order quickly.'
Sentiment: Positive

2. Sentence: 'The food was bland and the service was slow.'
Sentiment: Negative

3. Sentence: 'The product is okay, but it's not worth the price.'
Sentiment: Neutral

Sentence: {sentence}
""" 

# To use Groq LLMs 
model_name = "llama3-70b" # We can choose any model from the groq_models dictionary
llm = ChatGroq(model=groq_models[model_name], api_key=Groq_Token, temperature=0)
answer = llm.invoke(query)

print(answer.content)